name = "kosmolugika-v01"
main = "worker.js"
compatibility_date = "2026-09-29"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "kosmolugika"
database_id = "6c17f416-cb66-4dd5-93c6-919d6bd52e1a"
migrations_dir = "migrations"
